baseURL = 'https://yansheng.us.kg/'
languageCode = 'zh-cn'
title = 'yansheng'
theme = "github.com/CaiJimmy/hugo-theme-stack/v3"

[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[params]
    mainSections = ["post"]
    featuredImageField = "image"

    [params.sidebar]
        emoji = "ğŸš€"
        title = "yansheng"
        subtitle = "æ­£åœ¨æŠ˜è…¾çš„æå®¢"
        # ä¿®å¤å…³é”®ï¼šå¤´åƒå¿…é¡»ç”¨è¿™ç§èŠ±æ‹¬å·æ ¼å¼é…ç½®
        avatar = { enabled = true, local = true, src = "avatar.png" }

    [params.article]
        showReadingTime = true
        showWordCount = true

    # åŠ ä¸Šè¿™ä¸ªå¯ä»¥é˜²æ­¢æœç´¢åŠŸèƒ½æŠ¥é”™
    [params.search]
        enabled = false
