baseURL = 'https://yansheng.us.kg/'
languageCode = 'zh-cn'
title = 'yansheng' # è¿™é‡Œçš„æ ‡é¢˜ä¼šæ˜¾ç¤ºåœ¨æµè§ˆå™¨æ ‡ç­¾é¡µ
theme = "github.com/CaiJimmy/hugo-theme-stack/v3"

[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[params]
    mainSections = ["post"]
    featuredImageField = "image"

    [params.sidebar]
        emoji = "ğŸš€"
        subtitle = "æ­£åœ¨æŠ˜è…¾çš„æå®¢"
        # è¿™é‡Œçš„åå­—ä¼šæ˜¾ç¤ºåœ¨ä¾§è¾¹æ å¤´åƒä¸‹é¢
        title = "yansheng" 

    [params.article]
        showReadingTime = true
        showWordCount = true
