baseURL = 'https://yansheng.us.kg/'
languageCode = 'zh-cn'
title = 'yansheng' # è¿™é‡Œçš„æ ‡é¢˜ä¼šæ˜¾ç¤ºåœ¨æµè§ˆå™¨æ ‡ç­¾é¡µ
theme = "github.com/CaiJimmy/hugo-theme-stack/v3"

[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[params]
    mainSections = ["post"]
    featuredImageField = "image"

        [params.sidebar]
        emoji = "ğŸš€"
        subtitle = "æ­£åœ¨æŠ˜è…¾çš„æå®¢"
        title = "yansheng"
        avatar = "avatar.png"  # åŠ¡å¿…åŠ ä¸Šè¿™ä¸€è¡Œï¼Œå¦åˆ™å¤´åƒæ˜¾ç¤ºä¸å‡ºæ¥

    [params.article]
        showReadingTime = true
        showWordCount = true
